### ISSUE TITLE
Issue with Loading Certain Enemies When Using Korean Patch with Moguri Mod

### ISSUE THREAD

**Issue by LDDouble** [Albeoris/Memoria#1007]
Hi, I'm a Korean player of Final Fantasy IX.  

Since FF9 does not officially support the Korean language, we have been applying an unofficial fan patch by translating and replacing resource assets with Korean translations.  

There were no issues before, but since the Moguri Mod update on **November 19, 2024**, some enemies fail to load, causing the game screen to freeze and making further progress impossible.  

This issue does not occur when only the Moguri Mod is applied, but it does happen when both the Moguri Mod and the Korean patch are used together.  

## Steps to Reproduce  

- **Korean asset files:** [Download Link](https://drive.google.com/file/d/14B4r9q0LZ9ibekpSmtwr7enewJw5kzNZ/view?usp=sharing)  
- **Save file:** [Download Link](https://drive.google.com/file/d/1YjKLIiACaYOOJTnJq-G6klwFEBmBSacK/view?usp=sharing)  

### Behavior in the provided save file:  

- The enemy **"Ghost"** loads properly.  
- However, when the enemy **"Vice"** appears, the game fails to load and freezes.  
- If I apply a Moguri Mod version from before November 19, 2024, enemy names appear as "EnemyDummy", but the game still loads properly.

## Additional Information  

Memoria logs stop updating after the following entries, making it difficult for me to determine the exact cause:  

```
12.01.2025 01:53:03 |M| Map: 402 | Scenario counter: 2730
12.01.2025 01:53:08 |M| InitializeBattleText
```

This issue might not be exclusive to the Moguri Mod itself, but I wanted to ask if you could help investigate the problem.  

Thank you for creating such an amazing mod!

**Comment by Tirlititi** [comment]
Hello. Thanks a bunch for reporting the problem. I'll check and try to convert the mod to a version that can be used with the recent versions of Memoria / Moguri.

I'll try to find why it bugs as well: although we changed the way we handle translation mods nowadays, the old methods should still work (especially the method used for this Korean patch).

Are you one of the authors of this Korean translation, or do you know how to contact the authors?
If they agree, we can add the translation in the Mod Catalog, so it will be available from the launcher.

**Comment by LDDouble** [comment]
First of all, I want to sincerely thank you for the quick response.

I am not the author of the Korean translation, but I do have the author's email address.
Although the translation has not been updated since 2017, so I’m not sure if I’ll get a response, I will try reaching out.

**Comment by grantchester102** [comment]
Hi, I was just curious if anyone found a solution for this. I wanted to report that not just Vice, but encountering Axolotl, and Quale in Qu's Marsh also freezes the game. And just like OP said, when I downgrade the Memoria to August 24, 2024 version, the game doesn't freeze, but enemys name and its skills appears as "EnemyDummy".

Edit: To give more info on freeze, when I encounter Axolotl, the screen does spins a bit, and then when it shows the battle field, I only see the feet geo of Axolotl on the ground, but the body geos are not showing up, and as soon as that feet geo appears on battle field, the game crashes, no ally's visible, just the Axolotl's feet and the battle field.

Edit 2: When I changed the language from main menu such as to French or Spanish and encouter Axolotl, the games doesn't freeze.

**Comment by WarpedEdge** [comment]
Just a wildcard, but have you tried the recent canary patch from the
Releases, not Stable? Give that a go and just check and see if any issues
were resolved, it will prompt you to update the launcher, but click no
since it will bring you back to Stable currently. If that does not work you
can try attaching your Memoria.log here (attach not copy and paste) after
it happens so maybe we can see something.

**Comment by grantchester102** [comment]
Hi, thank you so much for the answer!

As you instructed, I've downloaded the Canary patch 'Memoria.Patcher.exe' that was uploaded 12 hours ago, and tried installing along with the Korean patch files, but the game still feeezes unfortunately.

I've attached the Memoria.log file and also a screenshot of frozen game here. Also, I found that techinacally, the program itself is not really frozen, but just the game loading seems frozen as I can see that the sky texture is slowly moving on background, the battle music still plays, and the F1- F4 cheat icons on lower right screen still appears on and off when I pressed them. So the game is still running, but just the loading of the monster seems like it's blocking the progress of the game.

Thank you so much again, for looking into this!

[Memoria.log](https://github.com/user-attachments/files/31600660/Memoria.log)

<img width="1922" height="1107" alt="Image" src="https://github.com/user-attachments/assets/3ce5cd8a-2d23-41fc-badb-c2aa751b8fbd" />

**Comment by WarpedEdge** [comment]
Okay log does not show anything for me. Does it eventually ever crash or
does it generate a crash folder in `x64` with the date?

**Comment by grantchester102** [comment]
I just checked x64 folder, but couldn't found 'Crash' folder, because the game is not really crashing to desktop, but it is still running, just frozen like that screenshot, so I still have to click X (Close) on window and confirm yes to close the game.

Just for testing, I tried leaving the frozen game for about 10 minutes, but it just stays like that, sky texture still continues to keep moving with music playing on background, so I closed the game manually with X (Close).

**Comment by WarpedEdge** [comment]
Hmm I am sorry about that, maybe someone else knows a way to debug further?
Or a log I am not seeing, but you said it is the korean patch specifically,
but if you for example try and download any other language patch it works
fine? I wonder if that mod just needs to be updated and something in it is
just hooking into something old.
