### ISSUE TITLE
Stat growths and formulas (Memoria.ini)

### ISSUE THREAD

**Issue by arg-xd** [Albeoris/Memoria#229]
Hello, playing with Moguri mod with latest Memoria applied over it and added Beatrix mod (don't think this should cause any conflicts).

Just got Eiko and her stats were off from what I expected so I went meddling in memoria .dat save files to manually transfer the stats, but even then Magic Stones were off by 1 so I checked BaseStats.csv and it turns out you gave her 1 less base (Eiko;6;19;13;21;18;**12**) than what is listed in every existing resource (**13**).

What surprised me though when inspecting the savefile I noticed all the characters joining before Eiko got maximum MStone bonus, as if they were auto leveled from 1 (for example Beatrix joined at 14, gained a level in forced battles and now her entry has 70 bonus MS), and from what I remember this is not natural behavior, base stat bonuses (0/3/3/1/5) are lost forever if game levels the characters for you. The behavior is inconsistent with Eiko though - Eiko joining at 15 had 10 bonus MS, while Marcus joined at 5 and left at 15 and has 70, Eiko's numbers make no sense whatsoever. Othervise all other base bonuses (str/mag/spr) work consistently and are lost in auto level ups.

Finally what caught my eye is when Memoria patcher creates the Memoria.ini it allows changing stat growths and states correct default formulas:

	; SpiritStatFormula (default: Min(50, SpiritBase + Level * 3 / 20 + (SpiritBonus / 32))) Formula for the level progression of player character spirit
	; MagicStoneStockFormula (default: Min(99, MagicStoneBase + Level * 4 / 10 + (MagicStoneBonus / 32))) Formula for the level progression of player character magic stones

but then in actual settings default is created as:

SpiritStatFormula = Min(50, SpiritBase + Level * 3 / 20 + (SpiritBonus >> 5))
MagicStoneStockFormula = Min(99, MagicStoneBase + Level * 4 / 10 + (MagicStoneBonus >> 5))

What would the (SpiritBonus >> 5) even return here?

**Comment by Tirlititi** [comment]
The operation ``>>`` is a [bit-shift](https://en.wikipedia.org/wiki/Logical_shift) operation. Basically, for two numbers ``A`` and ``B``, you have ``A >> B == A / (2 ^ B)``. So both formulas are the same there (since ``2^5 == 32``). Historically, bit-shifts were much faster operations than division, so you find them everywhere in source code of PSX games and before that. Now the computation speed difference is much less significant though.

About the change in Eiko's starting Magic Stone, I surely lowered it just a bit because she has Auto-Regen as soon as you get her in disc 2 and I wanted to put a cost on it that is a bit more significant.

About the behaviour in the level up bonuses and how exactly they increase, I'm afraid I don't know exactly how/when this behaviour changed. I think the original PC version was slightly different from the PSX version, then they made an official patch about it, and normally Memoria shouldn't change the behaviour after that patch, except maybe for the characters that used to share a slot (Marcus/Eiko, Blank/Amarant, Cinna/Quina). But even that, I think the official patch already kind of removed the Eiko/Marcus stat glitch before Memoria did anything.
Normally, having Beatrix (or any other character) joining the party at lvl 14 should indeed make a difference compared to what would happen if she joins at lvl 1 and get to lvl 14 through level ups. If that doesn't make any difference, I think we can say that's a bug, very possibly one that I introduced somehow.

**Comment by arg-xd** [comment]
RIP Eiko

Ok, onto the MS bonus issues now:

1. About PC version fixes I found this:

"What's New in Version 1.1.3

- We have corrected the amount of Magic Stones that transfer from Marcus to Eiko when she joins the party.
(The amount of Magic Stones in games where Eiko has already joined the party will also be corrected based on level. However, the amount of Magic Stones that transfer from Marcus in future may vary. New games and games where Eiko was added to the party only after the update should function normally. Thank you for your patience.)
- We have fixed the bug where disembarking from a Chocobo or airship can cause Zidane to disappear and players to be unable to progress in the game. Please update affected games to the newest version to fix the bug.
- Other minor bugs fixed."

Few points:
- Notice how it only talks about Magic Stones, leading me to believe the Tantalus trio are still sharing the data with Quinna/Eiko/Amarant, but due to how stats are calculated only the bonuses are persistent through char switch (more on that later)
- Now if you're still sharing the slot that means you either reinitialize the value when char joins or apply a persistent formula, however they further state "The amount of Magic Stones in games where Eiko has already joined the party will also be corrected based on level." which implies it is a persistent formula of MSbonus = 5*(Level-1), but the sentence after that makes no sense and the 3rd sentence is kind of ambiguous too as to me normal was the PSX behavior and persistent formula is not normal

This would explain why all of my chars before Eiko have 5*(Level-1) bonus MS, regardless of join level, but not what I had found on Eiko after she joined me (10 bonus MS implies 2 level ups and she got none from the time where she joined at 15 to the save I made before Madain Sari (which I backed up before inspecting the stats and messing with .dat, sadly I have no save backups before she joined to check what was in Eiko's block before she joined and how it changed during joining, bonus spd/str/mag/spr were empty obviously).

Aditionally Amarant joined with 0 bonus MS which is as it should be in original release but not with what I've seen so far here. Maybe the formula above is ran on some specific times, it surely is not on level up because leveling up only added 5 bonus MS, and Blank for example never leveled, joined and left at level 2 and his bonus MS is 5

2. About dual save system

Now you probably know this better since this tool implemented this functionality, it seems that bonus stats found in memoria save and base character stats override everything stat related (except current HP/MP), and also propagate into base game save so inspecting that (using the memoria save editor, because GL trying to read that) doesn't really give out any useful information, what's worse he doesn't even seem to know where bonus stats are stored in there, but considering he still keeps duality function on Quina/Cinna, Marcus/Eiko and Amarant/Blank would suggest it is/was still shared data on 2020 tool update.

However I'm not entirely convinced it is due to Tantalus trio separation in your save system as Quina still got 70 stones at level 15 despite joining at 5, sadly I only ran through game on one save so I can't really go through and check when and how this came to be. Since I manually edited Eiko to Marcus as intended, Amarant is the only one that is now outside of 5*(Level-1) formula, so I'll see how he fares with time.

Perhaps for testing purposes I should also reduce Freya/Quina MS bonus by 5 and see if they revert to the formula again. Eiko and Amarant are a bit of oddballs after all, due to their stat inheritance, but while Eiko does not inherit level Amarant does, so clearly join scripts there are not consistent to boot. I'll get back with info on this after the split in Oeilvert/Palace split.

**Comment by Tirlititi** [comment]
About the ``MSbonus`` correction, it almost certainly corresponds to [these lines](https://github.com/Albeoris/Memoria/blob/85362db582a0f8cf02e40d7c529a8e4dbee188a0/Assembly-CSharp/Global/JsonParser.cs#L339) in the source code: when loading a save, if the bonus stones was not initialized yet (or if the character was at level 1 the previous time), it is initialized to the formula you found, ``5 * (level - 1)``. Additionally, Eiko gets another bonus based on her level tens (+10 if she's level 10 or less, +20 if she's level 11-20, etc...). I'm pretty sure the ``getExtraCap`` method is what this patch log refers to.

It looks like this bonus is given to characters when you first load a saved game after they join the party. If you play through the game without ever re-loading a save, they won't benefit from this specific magic stone bonus.

**Comment by Tirlititi** [comment]
Ah indeed, ``bonus.cap`` is also given +5 on level up, it's not increased only when loading a game. My bad.
I think that the behaviour with Eiko getting +10 at the very start without waiting for Marcus's datas to turn into Eiko's datas is indeed a new behaviour of Memoria only due to the fact they don't share their character slot anymore.

I still have the source code of a very old version of the PC remaster (2016) and this code in JsonParser.cs was already there, with ``getExtraCap`` giving the same bonuses. So I actually don't know what this patch note refers to.
